apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n1
  namespace: zsongau
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: nginx-ingress-1.41.3.tgz
      version: '1.41.3'
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 5m
  releaseName: nginx-1
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 2
